# -*- coding: utf-8 -*-
"""minchange.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pVdOEmmYAw2-Uz7in8jSkrRO0AjZnbfS
"""

def findMin(V):
	
	change = [1, 2, 5, 10, 20, 50,100, 500, 2000]
	n = len(change)
	ans = []
	i = n - 1
	while(i >= 0):
		while (V >= change[i]):
			V -= change[i]
			ans.append(change[i])
		i -= 1
	for i in range(len(ans)):
		print(ans[i], end = " ")
		
if __name__ == '__main__':
	n = int(input("Enter n="))
	print("Following is minimal number of change for", n, ": ", end = "")
	findMin(n)